# Generated by Django 3.1.6 on 2021-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='barcode',
            field=models.ImageField(default=1, upload_to='media/barcodes'),
            preserve_default=False,
        ),
    ]
